import type { NextPage } from "next";
import Head from "next/head";
import Store from "store2";
import useTheme from "../lib/hooks/useTheme";
import { Container, Main, Title, Description, CodeTag } from "../styles/shared";
import { ThemeVariant } from "../styles/theme";
import Button from "../components/Button";

const Home: NextPage = () => {
  const { setCurrentTheme } = useTheme();

  const handleClick = (theme: ThemeVariant) => {
    setCurrentTheme(theme);
    Store("current-theme", theme);
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <div>
          <Button onClick={() => handleClick("light")}>Light</Button>
          <Button onClick={() => handleClick("dark")}>Dark</Button>
        </div>
      </Main>
    </Container>
  );
};

export default Home;
